<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CrossVault.FoxDbf\CrossVault.FoxDbf.csproj" />
    <ProjectReference Include="..\..\src\CrossVault.FoxDbf.Data\CrossVault.FoxDbf.Data.csproj" />
    <ProjectReference Include="..\..\src\CrossVault.FoxDbf.Expressions\CrossVault.FoxDbf.Expressions.csproj" />
    <ProjectReference Include="..\..\src\CrossVault.FoxDbf.MicroVfp\CrossVault.FoxDbf.MicroVfp.csproj" />
  </ItemGroup>

</Project>
