namespace CrossVault.FoxDbf.Tests;

/// <summary>
/// Locates the repo's PUBLIC test data: the Ruby dbf gem fixtures, the VFP9-generated
/// fixtures under vfp_test/, and the Tastrade sample database (Microsoft's public FoxPro
/// sample — safe to ship). The repo root is found by walking up from the test output dir
/// to the .git entry — NOT CrossVault.FoxDbf.slnx, which only exists in the private
/// foxDBFInternal repo; this project also runs standalone from the public foxDBF repo,
/// which has no .slnx at all. Real customer data (data/, exportdata/) lives in
/// FixturesInternal instead (CrossVault.FoxDbf.Tests.Internal-only, never shipped in the
/// public sync).
/// </summary>
public static class Fixtures
{
    public static string RepoRoot { get; } = FindRepoRoot();

    /// <summary>ref/ruby-dbf/spec/fixtures — small dBase/FoxPro sample files with known structure.</summary>
    public static string RubyFixturesDir => Path.Combine(RepoRoot, "ref", "ruby-dbf", "spec", "fixtures");

    /// <summary>vfp_test/ — fixtures generated by the local VFP9 IDE (e.g. nulltest.dbf with real .NULL. values).</summary>
    public static string VfpTestDir => Path.Combine(RepoRoot, "vfp_test");

    /// <summary>Tastrade_VFPData/ — the public Microsoft Tasmanian Traders VFP sample DB (silver master): tastrade.dbc + 10 member tables, each with a .cdx (some with .fpt memos). Independent DBC/memo/CDX cross-check.</summary>
    public static string TastradeDir => Path.Combine(RepoRoot, "Tastrade_VFPData");

    /// <summary>ref/go-dbase/.../table — a VFP 0x32 TEST.DBF (+TEST.FPT) carrying memo + varchar (V) + varbinary (Q) + blob (W) + nullable columns and a _NullFlags system column. The richest single mixed-type VFP fixture in the repo.</summary>
    public static string GoDbaseTableDir => Path.Combine(RepoRoot, "ref", "go-dbase", "examples", "test_data", "table");

    public static string Ruby(string name) => Path.Combine(RubyFixturesDir, name);
    public static string GoDbase(string name) => Path.Combine(GoDbaseTableDir, name);
    public static string VfpTest(string name) => Path.Combine(VfpTestDir, name);
    public static string Tastrade(string name) => Path.Combine(TastradeDir, name);

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, ".git")) && !File.Exists(Path.Combine(dir.FullName, ".git")))
            dir = dir.Parent;
        return dir?.FullName
            ?? throw new DirectoryNotFoundException("Could not locate repo root (.git) above " + AppContext.BaseDirectory);
    }
}
