namespace CrossVault.FoxDbf.Tests;

/// <summary>
/// Locates the repo's PUBLIC test data: the Ruby dbf gem fixtures, the VFP9-generated
/// fixtures under vfp_test/, and the Tastrade sample database (Microsoft's public FoxPro
/// sample — safe to ship). The repo root is the nearest directory containing BOTH a src/
/// and a tests/ subdirectory, found by walking up from the test output dir, OR (if that
/// never matches — e.g. starting from Tests.Internal's own bin dir, which lives OUTSIDE
/// public/ as a sibling, so the walk never passes through it) by checking each ancestor's
/// own "public" subdirectory instead. Either way this resolves to "public/" in the private
/// foxDBFInternal repo, and to this project's own repo root when it runs standalone in the
/// public foxDBF repo (the subtree split strips the "public/" prefix — vfp_test/ and
/// Tastrade_VFPData/ must live under public/ too, NOT as private-repo-top-level siblings,
/// for this to resolve consistently everywhere). Real customer data (data/, exportdata/)
/// lives in FixturesInternal instead (CrossVault.FoxDbf.Tests.Internal-only, never shipped
/// in the public sync).
/// </summary>
public static class Fixtures
{
    public static string RepoRoot { get; } = FindRepoRoot();

    /// <summary>
    /// The private monorepo's true top level (parent of RepoRoot/"public/") — where the gitignored
    /// ref/ clones and (via FixturesInternal) data/exportdata/ live. Only ever resolved by code paths
    /// that run exclusively in the private repo (Internal tests, or the Ruby/GoDbase accessors below,
    /// which nothing in the Public test project calls) — never valid when running standalone in the
    /// public foxDBF repo, where there is no such parent.
    /// </summary>
    internal static string PrivateRepoRoot => Path.GetDirectoryName(RepoRoot)
        ?? throw new DirectoryNotFoundException("RepoRoot has no parent directory: " + RepoRoot);

    /// <summary>ref/ruby-dbf/spec/fixtures — small dBase/FoxPro sample files with known structure.</summary>
    public static string RubyFixturesDir => Path.Combine(PrivateRepoRoot, "ref", "ruby-dbf", "spec", "fixtures");

    /// <summary>vfp_test/ — fixtures generated by the local VFP9 IDE (e.g. nulltest.dbf with real .NULL. values).</summary>
    public static string VfpTestDir => Path.Combine(RepoRoot, "vfp_test");

    /// <summary>Tastrade_VFPData/ — the public Microsoft Tasmanian Traders VFP sample DB (silver master): tastrade.dbc + 10 member tables, each with a .cdx (some with .fpt memos). Independent DBC/memo/CDX cross-check.</summary>
    public static string TastradeDir => Path.Combine(RepoRoot, "Tastrade_VFPData");

    /// <summary>ref/go-dbase/.../table — a VFP 0x32 TEST.DBF (+TEST.FPT) carrying memo + varchar (V) + varbinary (Q) + blob (W) + nullable columns and a _NullFlags system column. The richest single mixed-type VFP fixture in the repo.</summary>
    public static string GoDbaseTableDir => Path.Combine(PrivateRepoRoot, "ref", "go-dbase", "examples", "test_data", "table");

    public static string Ruby(string name) => Path.Combine(RubyFixturesDir, name);
    public static string GoDbase(string name) => Path.Combine(GoDbaseTableDir, name);
    public static string VfpTest(string name) => Path.Combine(VfpTestDir, name);
    public static string Tastrade(string name) => Path.Combine(TastradeDir, name);

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (IsLogicalRoot(dir.FullName)) return dir.FullName;
            var publicSubdir = Path.Combine(dir.FullName, "public");
            if (IsLogicalRoot(publicSubdir)) return publicSubdir;
            dir = dir.Parent;
        }
        throw new DirectoryNotFoundException(
            "Could not locate repo root (a directory containing both src/ and tests/, directly or under public/) above "
            + AppContext.BaseDirectory);
    }

    private static bool IsLogicalRoot(string path) =>
        Directory.Exists(Path.Combine(path, "src")) && Directory.Exists(Path.Combine(path, "tests"));
}
